services:
  db:
    build:
      context: requirements/db
      dockerfile: Dockerfile
    container_name: wp_db
    restart: always
    env_file:
      - .env
    environment:
      DB_ROOT_PASSWORD: /run/secrets/db_root_pwd
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_root_pwd
    expose:
      - 3306
    networks:
      - inception

  wordpress:
    build:
      context: requirements/wp
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always
    env_file:
      - .env
    environment:
      WP_USER_PASS: /run/secrets/wp_user_pass
    secrets:
      - wp_user_pass
    expose:
      - 9000
    depends_on:
      - db
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      timeout: 10s
      retries: 3
      interval: 30s
      start_period: 60s

  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    volumes:
      - ./requirements/nginx/nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ~/ssl/:/etc/nginx/ssl:ro
      - wp_data:/var/www/html:ro
    ports:
      - "443:443"
    extra_hosts:
      - "taung.42.fr:172.17.0.1"
    init: true
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  db_data:
    driver_opts:
      type: 'none'
      o: bind
      device: /home/taung/data/db_data
  wp_data:
    driver_opts:
      type: 'none'
      o: bind
      device: /home/taung/data/wp_data

secrets:
  wp_user_pass:
    file: ./secrets/wp_user_pwd.txt
  db_root_pwd:
    file: ./secrets/db_root_pwd.txt
