services:
  nginx:
    image: nginx
    container_name: my_nginx
    restart: always
    volumes:
      - /home/taung/my-website:/my-website:ro
      - ./config/nginx/nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/ssl/:/etc/nginx/ssl:ro
    extra_hosts:
      - "taung.42.fr:172.17.0.1"
    ports:
      - "80:80"
      - "443:443"
