services:
  db:
    build:
      context: requirements/db
      dockerfile: Dockerfile
    container_name: wp_db
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - 3306
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$${DB_ROOT_PASSWORD}"]
      timeout: 10s
      retries: 5
      interval: 10s
      start_period: 30s

  wordpress:
    build:
      context: requirements/wp
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always
    env_file:
      - .env
    expose:
      - 9000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      timeout: 10s
      retries: 3
      interval: 30s
      start_period: 60s

  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    volumes:
      - ./requirements/nginx/nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ~/ssl/:/etc/nginx/ssl:ro
      - wp_data:/var/www/html:ro
    ports:
      - "443:443"
    extra_hosts:
      - "taung.42.fr:172.17.0.1"
    init: true
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  db_data:
    driver_opts:
      type: 'none'
      o: bind
      device: /home/taung/data/db_data
  wp_data:
    driver_opts:
      type: 'none'
      o: bind
      device: /home/taung/data/wp_data
