services:
  db:
    build:
      context: requirements/db
      dockerfile: Dockerfile
    container_name: wp_db
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my-custom-network

  wordpress:
    build:
      context: requirements/wp
      dockerfile: Dockerfile
    container_name: my_wordpress
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - wp_data:/var/www/html
    networks:
      - my-custom-network

  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: my_nginx
    restart: always
    volumes:
      - ./requirements/nginx/nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ~/ssl/:/etc/nginx/ssl:ro
      - wp_data:/var/www/html:ro
    ports:
      - "443:443"
    extra_hosts:
      - "taung.42.fr:172.17.0.1"
    init: true
    depends_on:
      - wordpress
    networks:
      - my-custom-network

networks:
  my-custom-network:
    driver: bridge

volumes:
  db_data:
   driver_opts:
      type: 'none'
      o: bind
      device: /home/thant-htet-aung/taung/data/db_data
  wp_data:
   driver_opts:
      type: 'none'
      o: bind
      device: /home/thant-htet-aung/taung/data/wp_data
