version: "3.8"

services:
  db:
    image: mariadb:latest
    container_name: wordpress_db
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - wpnet

  wp-fpm:
    image: wordpress:php8.2-fpm
    container_name: wordpress_fpm
    restart: always
    depends_on:
      - db
    volumes:
      - wp_content:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - wpnet

  nginx:
    image: nginx:alpine
    container_name: wordpress_nginx
    restart: always
    depends_on:
      - wp-fpm
    volumes:
      - wp_content:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro  # Optional SSL
    ports:
      - "80:80"
      - "443:443"
    networks:
      - wpnet

volumes:
  db_data:
  wp_content:

networks:
  wpnet:
